version: '3.8'

services:
  bot:
    build: .
    container_name: aiogram_bot
    env_file:
      - .env  # Load environment variables from the .env file
    volumes:
      - .:/app
    restart: always
